---
title: "Contribute"
output: 
    html_document:
        toc: TRUE
        toc_float: TRUE
---

# File bug reports

If you've found a bug you can help out by filing a bug report. Each package has an issue tracker where you can create a new issue. Try and be as specific as possible. What error message occurs? Can you provide a simple example to reproduce the problem? What versions of the various packages are you running?

# Write help files

If you're a bit more experienced with the Methods Library and are looking to improve your open source development skills, the next step up is to contribute a pull request to a Methods Library package. The most important thing to know is that Methods Library packages use [roxygen2](https://github.com/klutometis/roxygen): this means that documentation is found in the R code close to the source of each function. 

# Write unit tests

An important part of validating the methods in the library is unit testing. A unit test is a small program that tests a specific function in the library. For example, there are [several unit tests](https://github.com/OHDSI/CohortMethod/blob/master/tests/testthat/test-psFunctions.R#L5) that make sure the propensity score matching works correctly. We can never have enough unit tests, and writing unit tests is an excellent way to learn how the Methods Library packages work under the hood.

# Add methods

We are always looking for new methods and packages to add to the Methods Libary. However, in order to qualify for inclusion a package must meet the following requirements:

- Pass R check without warnings or notes.
- Adhere to [OHDSI's code style guidelines](https://ohdsi.github.io/MethodsLibrary/contribute.html#code_style_guidelines) and overall development practices.
- Have [unit tests](http://www.ohdsi.org/web/wiki/doku.php?id=development:unit_testing_in_r) that test the package's most important routines.
- For population-level estimation methods: be evaluated using the OHDSI Methods Benchmark.

# Code style guidelines

- [Style guide for R code](http://www.ohdsi.org/web/wiki/doku.php?id=development:ohdsi_code_style_for_r)
- [Style guide for SQL code](http://www.ohdsi.org/web/wiki/doku.php?id=development:ohdsi_code_style_for_sql)
